language: python
python:
  - 3.6

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install requests

script:
  - python -m unittest tests/test_code.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  provider: pages
  edge: true
  on:
    branch: master
